version: '3.4'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.0.0
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-abc-panel
      - ./provisioning:/etc/grafana/provisioning
